### ISSUE TITLE
terraform fmt

### ISSUE THREAD

**Issue by kostyrev** [jen20/hashidays-nyc#1]
Thank you for putting this up. it's very useful.
But please consider using `terraform fmt` to lint your code 'cause currently it's very hard to get through it.

**Comment by jen20** [comment]
Hi, sorry for the delay in replying to this, the notification was missed in the noise of GitHub notifications!

I'm not a huge fan of the `terraform fmt` annointed style - in particular lined up equals signs are a pet hate of mine, which is why I don't use it - sorry!
