### ISSUE TITLE
ELB instead of lambda

### ISSUE THREAD

**Issue by rokka-n** [jen20/hashidays-nyc#2]
Hi,

That's a cool demo and there are tons of interesting ideas. I didn't know that terraform has resources to manage tls.

I noticed you've used lambda to update route 53 records. Was there a special consideration to use lambda compared to internal ELB in ASG? ELB can do helthchecks as well for consul process (what if it's crashed or run out of disk space), so ASG can replace instances.

Thanks again for a cool project!

**Comment by jen20** [comment]
Sorry for the delay on replying to this, the notification got lost in my inbox. The reason for lambda vs an ELB is purely cost. I've also used an ELB successfully.
